apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patchesStrategicMerge:
- deployment-prod.yaml

namePrefix: prod-

namespace: prod

commonLabels:
  app: prod



