apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2 #my image
        ports:
        - containerPort: 80