apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 3 # Update the replica count to 3
  template:
    spec:
      containers:
      - name: dev-app
        image: ttl.sh/my-dev-app:12h

