apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: deployment-dev.yaml
- path: service-dev.yaml

namePrefix:
  dev-

commonLabels:
  app: dev

images:
- name: ttl.sh/my-dev-app #my dev app
  newTag: 12h #my dev app version



