apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- deployment-dev.yaml
#- service-dev.yaml
- namespace-dev.yaml

namePrefix:
  dev-

namespace: dev

commonLabels:
  app: dev

images:
- name: nginx
  newName: ttl.sh/my-dev-app
  newTag: 1d



