apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- path: deployment-dev.yaml
- path: service-dev.yaml

namePrefix:
  dev-

namespace: dev

commonLabels:
  app: dev




